name: food-atlas

networks:
  traefik_network:
    name: traefik_network
    external: true

services:
  swagger:
    image: docker.swagger.io/swaggerapi/swagger-ui
    volumes:
      - ./doc/food-atlas.yaml:/food-atlas.yaml
    environment:
      SWAGGER_JSON: /food-atlas.yaml
      BASE_URL: /api
    expose:
      - 8080
    networks:
      - traefik_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.swagger.entryPoints: https
      traefik.http.routers.swagger.rule: Host(`${FQDN}`) && PathPrefix(`/api`)
      traefik.http.services.swagger.loadbalancer.server.port: "8080"

  api:
    image: ghcr.io/julesrossier/food-atlas:latest
    pull_policy: always
    working_dir: /app
    command:
      - --populate-with-data
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.entryPoints: https
      traefik.http.routers.api.rule: Host(`${FQDN}`)
      traefik.http.services.api.loadbalancer.server.port: 8080

      traefik.http.middlewares.redirect-api.redirectregex.regex: "^https:\\/\\/([^\\/]+)\\/?$$"
      traefik.http.middlewares.redirect-api.redirectregex.replacement: "https://$$1/api/"
      traefik.http.routers.api.middlewares: redirect-api
#      traefik.http.routers.api.middlewares: redirectRegex
    networks:
      - traefik_network
    expose:
      - 8080
